-- MySQL Script generated by MySQL Workbench
-- 03/04/15 17:51:01
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema poesie
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `poesie` ;
CREATE SCHEMA IF NOT EXISTS `poesie` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `poesie` ;

-- -----------------------------------------------------
-- Table `poesie`.`auteur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poesie`.`auteur` ;

CREATE TABLE IF NOT EXISTS `poesie`.`auteur` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `prenom` VARCHAR(45) NULL,
  `nom` VARCHAR(45) NOT NULL,
  `naissance` DATE NULL,
  `deces` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'la table doit avoir une entrée spéciale: l\'auteur \"anonyme\".';


-- -----------------------------------------------------
-- Table `poesie`.`editeur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poesie`.`editeur` ;

CREATE TABLE IF NOT EXISTS `poesie`.`editeur` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `rue` VARCHAR(120) NULL,
  `code_postal` VARCHAR(6) NULL,
  `ville` VARCHAR(45) NULL,
  `pays` VARCHAR(45) NULL,
  `telephone` VARCHAR(16) NULL,
  `email` VARCHAR(60) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poesie`.`recueil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poesie`.`recueil` ;

CREATE TABLE IF NOT EXISTS `poesie`.`recueil` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(120) NOT NULL,
  `Editeur_id` INT UNSIGNED NOT NULL,
  `auteur_id` INT UNSIGNED NULL COMMENT 'La colonne \"auteur\" est facultative - un recueil peut avoir plusieurs auteurs (ex. anthologie)',
  `publication` DATE NULL,
  `disponible` TINYINT NULL COMMENT 'TRUE si disponible, FALSE si épuisé',
  `langue` VARCHAR(45) NULL,
  `ISBN` VARCHAR(16) NULL,
  `format` VARCHAR(16) NULL COMMENT 'format : \'relié\' / \'broché\' / \'poche\' / \'e-pub\' / \'mobi\'',
  `prix` DECIMAL(6,2) NULL COMMENT 'en Euros',
  PRIMARY KEY (`id`),
  INDEX `fk_recueil_auteur_idx` (`auteur_id` ASC),
  INDEX `fk_recueil_Editeur1_idx` (`Editeur_id` ASC),
  CONSTRAINT `fk_recueil_auteur`
    FOREIGN KEY (`auteur_id`)
    REFERENCES `poesie`.`auteur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recueil_Editeur1`
    FOREIGN KEY (`Editeur_id`)
    REFERENCES `poesie`.`editeur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poesie`.`poeme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poesie`.`poeme` ;

CREATE TABLE IF NOT EXISTS `poesie`.`poeme` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(120) NOT NULL,
  `texte` TEXT NULL COMMENT 'facultatif, le texte du poème',
  `auteur_id` INT UNSIGNED NOT NULL COMMENT 'ne peut pas être NULL: doit référencer l\'auteur \"anonyme\" si l\'auteur n\'est pas connu',
  `parution` DATE NULL,
  `fin_droits` DATE NULL COMMENT 'par convention la date peut être 1900 par exemple si le poème est très ancien et n\'a jamais été protégé.',
  PRIMARY KEY (`id`),
  INDEX `fk_poeme_auteur1_idx` (`auteur_id` ASC),
  CONSTRAINT `fk_poeme_auteur1`
    FOREIGN KEY (`auteur_id`)
    REFERENCES `poesie`.`auteur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poesie`.`recueil_poeme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poesie`.`recueil_poeme` ;

CREATE TABLE IF NOT EXISTS `poesie`.`recueil_poeme` (
  `recueil_id` INT UNSIGNED NOT NULL,
  `poeme_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`recueil_id`, `poeme_id`),
  INDEX `fk_recueil_has_poeme_poeme1_idx` (`poeme_id` ASC),
  INDEX `fk_recueil_has_poeme_recueil1_idx` (`recueil_id` ASC),
  CONSTRAINT `fk_recueil_has_poeme_recueil1`
    FOREIGN KEY (`recueil_id`)
    REFERENCES `poesie`.`recueil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recueil_has_poeme_poeme1`
    FOREIGN KEY (`poeme_id`)
    REFERENCES `poesie`.`poeme` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
